#!/usr/bin/env ruby
dir = File.dirname(__FILE__)
root = File.expand_path("#{dir}/..")

require "#{root}/config/boot"
require "activesupport"
require File.join(dir, '..', 'vendor', 'plugins', 'screw-unit-server', 'lib', 'screw_unit')
ScrewUnit::RailsServer.run(root)
